version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - "9090:9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml 
    - --log.level=debug
    volumes:
    - ./conf/prom-conf.yml:/etc/prometheus/prometheus.yml:ro


  sampleapp:
    image:  sampleapp:1.0
    container_name: sampleapp
    ports:
    - 9091:9091
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 100M
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

